services:
  aviation-missions:
    image: aviation-missions:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "${PORT:-8080}:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - API_PORT=3000
    # Set healthcheck to ensure container is running properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s