services:
  aviation-missions:
    image: aviation-missions:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend  # Mount backend for development
      - ./frontend:/app/frontend  # Mount frontend for development
    restart: unless-stopped
    environment:
      - ENVIRONMENT=development
      - PORT=${PORT:-8080}
      - API_PORT=${API_PORT:-3000}
    # Set healthcheck to ensure container is running properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
