name: 🔒 Security Report
description: Report a security vulnerability (for public issues only)
title: "[Security]: "
labels: ["security", "triage"]
assignees:
  - jordanhubbard
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Important Security Notice
        
        **For sensitive security vulnerabilities, please DO NOT use this public issue tracker.**
        
        Instead, please report sensitive vulnerabilities privately using:
        - GitHub Security Advisories: [Report a vulnerability](https://github.com/jordanhubbard/aviation-missions-app/security/advisories/new)
        - Email the maintainer directly
        
        **Only use this form for non-sensitive security improvements or general security discussions.**
        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      
  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Low - General security improvement
        - Medium - Potential security concern
        - High - Confirmed security issue (use private reporting)
        - Critical - Active security vulnerability (use private reporting)
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the security concern or improvement suggestion
      placeholder: Please provide a clear description...
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the application is affected?
      options:
        - Frontend
        - Backend API
        - Database
        - Authentication
        - Docker/Infrastructure
        - Dependencies
        - Documentation
        - Other (specify in description)
    validations:
      required: true
      
  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could happen if this security issue is not addressed?
    validations:
      required: true
      
  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for how to fix this issue, please describe them here.
    validations:
      required: false
      
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: This is NOT a sensitive vulnerability that could be exploited
          required: true
        - label: I have considered reporting this privately if it's sensitive
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true
